const APP_DESCRIPTION = import.meta.env.VITE_APP_DESCRIPTION;
const APP_SHORT_DESCRIPTION = import.meta.env.VITE_APP_SHORT_DESCRIPTION;
const APP_NAME = import.meta.env.VITE_APP_NAME;
const API_URL = import.meta.env.VITE_API_URL;

export { APP_DESCRIPTION, APP_NAME, APP_SHORT_DESCRIPTION, API_URL };
