const APP_DESCRIPTION = import.meta.env.VITE_APP_DESCRIPTION;
const APP_SHORT_DESCRIPTION = import.meta.env.VITE_APP_SHORT_DESCRIPTION;
const APP_LONG_DESCRIPTION = import.meta.env.VITE_APP_LONG_DESCRIPTION;
const APP_NAME = import.meta.env.VITE_APP_NAME;
const OPENAI_KEY = import.meta.env.VITE_OPENAI_KEY;

export {
  APP_DESCRIPTION,
  APP_NAME,
  APP_LONG_DESCRIPTION,
  APP_SHORT_DESCRIPTION,
  OPENAI_KEY,
};
